# Generated by Django 4.0.4 on 2025-04-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
